server:
  port: 8083

spring:
  #  Test Database (PostgreSQL on port 5433)
  datasource:
    url: jdbc:postgresql://localhost:5433/communityboard_test
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none   # don't auto-create/drop schema in test DB
    show-sql: true
    properties:
      hibernate:
        format_sql: true
